#!/bin/sh
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ZK_PORT=${1:-2181}
OK=$(timeout -k 10 15s bash -c "echo ruok | nc -w 2 -q 1 localhost $ZK_PORT | grep imok")

if [ "$OK" = "imok" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S') - INFO - ruok command response: imok"
	exit 0
else
	echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR - ruok command response: notok"
	exit 1
fi